// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcodmzyfcndyiwixjkst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjb2RtenlmY25keWl3aXhqa3N0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyMDkyMjgsImV4cCI6MjA2MTc4NTIyOH0.70yKpMI7yJSBl1ZJ95nTHk0T9EFqLmJh7x1-5ZyRJ0A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);